**Data Manipulation:**

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [6]:
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [7]:
import numpy as np

In [9]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [10]:
a*b

array([ 2,  6, 12, 20])

_Numpy Array:_

In [11]:
import numpy as np

In [12]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
np.array([2,3.4,6,7,8])

array([2. , 3.4, 6. , 7. , 8. ])

In [14]:
np.array([2, 3.4, 6, 7.8], dtype ="int")

array([2, 3, 6, 7])

In [17]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.arange(0,32, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [22]:
np.linspace(0,1, 8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [23]:
np.random.randint(0,10, (3,4))

array([[3, 0, 2, 1],
       [1, 1, 9, 7],
       [7, 1, 3, 6]])